spring:
  application:
    name: minidooray-team8-task-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/nhn_academy_8?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: nhn_academy_8
    password: zq#ueLhsLMT258C?

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true