# Server Port
server.port=8082

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://10.116.64.14:13306/nhn_academy_35
spring.datasource.username=nhn_academy_35
spring.datasource.password=axMR@qTbrJmguez4
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Init
spring.sql.init.mode=never
#spring.sql.init.schema-locations=classpath:sql/ddl.sql
spring.sql.init.data-locations=classpath:sql/dummy-data.sql